# Generated by Django 2.2 on 2021-01-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('UpdatedAt', models.DateField(auto_now_add=True)),
                ('CreatedAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
